### ISSUE TITLE
tree_detection is deprecated. Use find_trees instead.

### ISSUE THREAD

**Issue by adminmyw** [r-lidar/lidR#513]
when I USE CHM.tif file to Get treetops it shows：tree_detection is deprecated. Use find_trees instead.

what should I do to deal with it？

code：
ttops <- tree_detection(chm, lmf(ws=ws, hmin=hmin, shape="circular")) # Get treetops
    crowns <- dalponte2016(chm, ttops, th_tree=hmin, th_seed=0.65, th_cr=0.5,
                           max_cr=5)() # Segment

ERROR：tree_detection is deprecated. Use find_trees instead.

**Comment by Jean-Romain** [comment]
`tree_detection()` is deprecated since one year an a half. See the [changelog v3.0.0](https://github.com/r-lidar/lidR/blob/master/NEWS.md#lidr-v300-release-date-2020-06-08). The function printed message, then warning, now error. Please keep you packages up-to-date. It is not reasonable to update your packages less than once per year. Use `find_trees` instead of `tree_detection`
