### ISSUE TITLE
Marker Controlled Watershed

### ISSUE THREAD

**Issue by azh2** [r-lidar/lidR#542]
Are there any plans to include a new marker-controlled watershed function in the near future? I am currently using the mcws function in the Forest Tools package inside a user-defined catalog function.

**Comment by Jean-Romain** [comment]
Actually the marker controlled watershed was removed in version [2.2.1](https://github.com/r-lidar/lidR/blob/6bffbafa686369fee1a75e9e7b8f075075e589bb/NEWS_v2.md#lidr-v221--release-date-2020-01-21)

> `imager` was used to drive the `mcwatershed()` algorithm. `imager` is an orphaned package that generated a warning on CRAN. Consequently mcwatershed() has been removed. In attempt to provide an informative message to users, the function still exists but generates an error. Anyway this method was weak and buggy and it was a good reason to remove it...

The marker controlled watershed was exactly the same than in `ForestTools`. Both relies on `imager`. It seems that `imager` is no longer orphaned but anyway I won't add back `mcwatershed` in `lidR` because I don't want to add a new dependency. However we can easily bring back `mcwatershed` to life by making a plugin

```r
mcwatershed = function(chm, treetops, th_tree = 2, tol = 1, ext = 1)
{
  f = function(bbox)
  {
    if (!missing(bbox)) chm <- raster::crop(chm, bbox)
    
    # Convert the CHM to a matrix
    Canopy <- raster::as.matrix(chm)
    mask   <- Canopy < th_tree | is.na(Canopy)
    Canopy[mask] <- 0
    
    cells <- raster::cellFromXY(chm, sf::as_Spatial(treetops))
    ids <- seq_along(cells)
  
    seeds = chm
    seeds[] = 0L
    seeds[cells] = ids
    treetops = raster::as.matrix(seeds)
    
    Canopy <- Canopy/max(Canopy)
    Canopy <- imager::as.cimg(Canopy)
    treetops  <- imager::as.cimg(treetops)
    Crowns <- imager::watershed(treetops, Canopy)
    Crowns <- Crowns[,,1,1]
    storage.mode(Crowns) = "integer"
    
    Crowns[mask] <- NA_integer_
    Crowns = raster::raster(Crowns)
    raster::extent(Crowns) = raster::extent(chm)
    
    return(Crowns)
  }
  
  f <- lidR::plugin_its(f, raster_based = TRUE)
  return(f)
}

library(lidR)
LASfile <- system.file("extdata", "MixedConifer.laz", package="lidR")
las <- readLAS(LASfile, select = "xyzi")
col <- pastel.colors(250)

chm <- rasterize_canopy(las, res = 0.5, p2r(0.3), pkg = "raster")
ker <- matrix(1,3,3)
chm <- raster::focal(chm, w = ker, fun = mean, na.rm = TRUE)
treetops <- locate_trees(chm, lmf(3))

las <- segment_trees(las, mcwatershed(chm, treetops))
plot(las, color = "treeID")
res <- crown_metrics(las, ~mean(Intensity), geom = "convex")
plot(res["V1"], pal = heat.colors)

crowns <- mcwatershed(chm, treetops)()
plot(crowns, col = pastel.colors(150))
```

Notice some limitations compared to other algorithm in `lidR`. This versions is

- Not raster agnostic. It works only with a `RasterLayer` because I extracted that from an old version. But you can easily make changes to work with `SpatRaster`.
- Not as safe as other functions. I dropped many tests performed by internal functions in `lidR`
