### ISSUE TITLE
Using noise filtering function with parallel computation

### ISSUE THREAD

**Issue by AndresKasekamp** [r-lidar/lidR#603]
I am using a noise filtering found [here](https://cran.microsoft.com/snapshot/2020-04-20/web/packages/lidR/vignettes/lidR-catalog-apply-examples.html). I have slightly modified internal behavior, but the general blueprint has stayed the same. As I have a lot of data to process, I was wondering if parallelism is a possibility. There seems to be some restrictions when trying to process an LAScatalog and I have encountered an error message:

```
Error: no applicable method for 'lasfilternoise' applied to an object of class "LAScluster"
```

Is there any way to overcome this? Where should I but multiprocessing parameters, found [here](https://rdrr.io/cran/lidR/man/lidR-parallelism.html).

Right now they are on top of my script, like so:

```r
library(future)

plan(multisession, workers = 2L)
set_lidr_threads(2L)
```

**Comment by Jean-Romain** [comment]
First advice, stop reading documentation from third party sources such as `rdrr.io`, `rdocumentation.com` or worst: `microsoft.com`. Like several other users you are reading a 2 year old pages that corresponds to version 2.2.3. We are at version 4.0.1. The documentation from the [CRAN](https://cran.r-project.org/web/packages/lidR/index.html) is guaranteed to be up-to-date. My [book](https://r-lidar.github.io/lidRbook/) is also up-to-date (if you do not read it from mirror places).

In the [up-to-date vignette](https://cran.r-project.org/web/packages/lidR/vignettes/lidR-catalog-apply-examples.html) I changed the example because parallelism was problematic with the former syntax if the code is not in a package. With the current syntax  it should work out of the box.
